# This playbook installs packages which are
# required on the management server.
---
- name: install basic software
  hosts: localhost
  become: true
  become_user: root
  tasks:
  - name: install pip
    apt:
      name: python-pip
