---
- name: main playbook of all the task for all the kinds of servers
  hosts: localhost

  vars_files:
    - vars.yml

  connection: local
  gather_facts: no

  tasks:
    # Packages required by the management server
    - include_tasks: tasks/common.yml
    # Create a new GCP instance
    - include_tasks: tasks/instance.yml instance_name="{{ instances.name }}" instance_group="{{ instances.group }}"
      with_items:
        - {name: loadbalancer, group: loadbalancer}
        - {name: server1, group: server}
#         - {name: server2, group: server}
        - {name: database, group: database}
        # - {name: backup, group: backup}
        # - {name: ldap, group: ldap}
      loop_control:
        loop_var: instances

- hosts: database

  # switch user
  become: true
  become_user: root

  roles:
    - mysql
  tasks:
    - name: show all the hosts matching the pattern, i.e. all but the group www
      debug:
        msg: "{{ item }}"
      with_inventory_hostnames:
        - all:!www

- name: install web server software
  hosts: server

  # switch user
  become: true
  become_user: root
  gather_facts: no

  roles:
    - apache
    - php
    - owncloud

