---
- name: Create instance(s)
  hosts: localhost
  
  vars_files:
    - vars.yml

  connection: local
  gather_facts: no
  tasks:
    # Packages required by the management server
    - include_tasks: common.yml
    # Create a new GCP instance
    - include_tasks: instance.yml instance_name="{{ instances.name }}" instance_group="{{ instances.group }}"
    # Setup the web platform on the new instance
    - include_tasks: web.yml
