---
- name: setup ansible controller
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - include_tasks: playbooks/tasks/common.yml
    - include_tasks: playbooks/tasks/instance_common.yml


- import_playbook: playbooks/nfs.yml
- import_playbook: playbooks/webserver.yml
- import_playbook: playbooks/database-server.yml