---
- name: setup ansible controller
  hosts: localhost
  connection: local
  gather_facts: no

  #--------------------------------------------
  # Build the inventory (order doesn't matter)
  #--------------------------------------------
  vars_files:
    - playbooks/vars/vars.yml
  vars:
    # what instances to create?
    instances:
      - group: database
        names: db01
      - group: webserver
        names: ws01,ws02
      - group: nfs
        names: nfs01
      - group: loadbalancer
        names: lb01

    # what instance to attach disk to?
    disks:
      instances:
        - nfs01
      disk_size: 50

  tasks:
    - name: setup the ansible controller
      include_tasks: playbooks/tasks/common.yml

    - name: configure the firewall
      include_tasks: playbooks/tasks/configure_firewall.yml

    - name: create instances(s)
      include_tasks: playbooks/tasks/gce_create_instance.yml
      vars:
        instance_name: "{{ node.names }}"
        instance_tags: ["{{ node.group }}"]
        instance_group: "{{ node.group }}"
      with_items:
        - "{{ instances }}"
      loop_control:
        loop_var: node
    - name: show
      debug: var=hostvars
    - name: show
      debug: var=groups
    - name: show
      debug: var=ansible_all_ipv4_addresses
    - name: create disk(s)
      include_tasks: playbooks/tasks/gce_create_volume.yml
      vars:
        instance_name: "{{ item }}"
        disk_name: "{{ item }}-disk"
        disk_size: "{{ disks.disk_size }}"
      with_items:
        - "{{ disks.instances }}"


# The reason these playbooks are separated is so
# if someone needs to create another 'server' such as 
# a NFS server they can run nfs.yml to set it up.
- import_playbook: playbooks/nfs.yml
- import_playbook: playbooks/database-server.yml
- import_playbook: playbooks/webserver.yml
- import_playbook: playbooks/load-balancer.yml
