---
- name: install gogs related
  hosts: new_instances
  vars_files:
    - vars.yml

  # switch user
  become: true
  become_user: root
  vars:
    


  tasks:
    - name: install all
      shell: sudo apt-get update

    - name: configure mysql user
      shell: wget https://raw.githubusercontent.com/mulinShi/key/master/updateRootForMysql

    - name: run mysql user
      shell: sudo bash updateRootForMysql

    - name: install apache
      become: true
      apt: name=apache2 state=latest
      apt: name=apache2-doc state=latest
      apt: name=apache2-utils state=latest

    - name: install mysql
      become: true
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: install mysql python module
      become: true
      apt:
        name: python-mysqldb
        state: present

    - name: start mysql
      become: true
      sudo: yes
      service:
        name: mysql
        state: started
        enabled: true

    - name: php install
      become: true
      apt: name=php7.0 state=present
      apt: name=php7.0-mysql state=present

    - name: install php model
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
      - php
      - php-mysql
      - php-gd
      - php-zip
      - php-mbstring
      - php-xml
      - php-intl
      - php-curl

    - name: install php extensions
      become: true
      apt:
        name: libapache2-mod-php
        state: present
      notify:
        - restart apache2

    - name: configure owncloud
      shell: wget https://raw.githubusercontent.com/mulinShi/key/master/configureOwncloud.yml

    - name: run owncloud
      shell: sudo bash configureOwncloud.yml

  handlers:
    - name: restart apache2
      become: true
      service:
        name: apache2
        state: restarted
