- name: download apache-libcloud
  shell: pip install apache-libcloud

- name: get public-key
  shell: cat ~/.ssh/id_rsa.pub
  register: publickey

- name: who
  shell: whoami
  register: name

- name: Create Firewall Rule w/Source Tags
  gce_net:
    name: default
    project_id: "{{ project_id }}"
    credentials_file: ""
    service_account_email: ""
    fwname: "database"
    allowed: tcp:3306
    state: "present"
    target_tags: "database"

- name: Create Firewall Rule w/Source Tags
  gce_net:
    name: default
    project_id: "{{ project_id }}"
    credentials_file: ""
    service_account_email: ""
    fwname: "nfs"
    allowed: "tcp:111,2049;udp:111,2049"
    state: "present"
    target_tags: "nfs"