- name: install nfs
  apt:
    name: nfs-kernel-server

- name: create folder
  file: path=/ownclouddata state=directory

- name: add folder 1
  lineinfile:
    path: /etc/exports
    line: "/var/www/owncloud {{ item }}(rw)"
  with_inventory_hostnames:
    - server

- name: add folder 2
  lineinfile:
    path: /etc/exports
    line: "/ownclouddata {{ item }}(rw)"
  with_inventory_hostnames:
    - server

- name: service start
  service:
    name: nfs-kernel-server
    state: restarted
