- name: configure mysql password
  command: debconf-set-selections <<< 'mysql-server mysql-server/root_password password 123456'

- name: configure mysql password again
  command: debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password 123456'

- name: install mysql
  apt:
    name: "{{ item }}"
  with_items:
    - mysql-server
    - mysql-client

- name: install mysql python module
  apt:
    name: python-mysqldb

- name: start mysql
  service:
    name: mysql
    state: started
    enabled: true