- name: apt install nfs-common
  apt:
    name: nfs-common


- name: mount
  mount:
    path: /vars/www/owncloud
    src: "{{ item }}:/vars/www/owncloud"
    fstype: nfs
    state: mounted
  with_inventory_hostnames:
    - nfs