- name: apt install nfs-common
  apt:
    name: nfs-common

# sudo mount -t nfs 35.237.213.137:/vars/www/owncloud /vars/www/owncloud
- name: mount
  mount:
    path: /var/www/owncloud
    src: "{{ item }}:/var/www/owncloud"
    fstype: nfs
    state: mounted
  with_inventory_hostnames:
    - nfs
